# To learn about this file, please see https://www.gitpod.io/docs/references/gitpod-yml

# NOTE: Use Gitod's PostgreSQL image once https://github.com/gitpod-io/workspace-images/issues/705 is fixed
#image: gitpod/workspace-postgres
image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      rm ./renovate.json
      yarn install
    command: yarn redwood dev

ports:
  - port: 5432
    name: PostgreSQL database
    onOpen: ignore
  - port: 8910
    name: RedoodJS web application
    onOpen: open-browser
  - port: 8911
    name: Serverless functions
    onOpen: ignore

vscode:
  extensions:
    - "dbaeumer.vscode-eslint"
    - "eamodio.gitlens"
    # - "ofhumanbondage.react-proptypes-intellisense" - Not published to Open VSX (yet)
    - "mgmcdermott.vscode-language-babel"
    - "wix.vscode-import-cost"
    - "pflannery.vscode-versionlens"
    - "editorconfig.editorconfig"
    - "prisma.prisma"
    - "graphql.vscode-graphql"
