# To learn about this file, please see https://www.gitpod.io/docs/references/gitpod-yml

image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      createdb dev
      yarn install
      cp .env.defaults .env
      echo "SESSION_SECRET=$(yarn rw g secret | sed '2q;d' | xargs)" >> .env
      yarn rw prisma migrate dev
    command: yarn rw sb

ports:
  - port: 5432
    name: PostgreSQL database
    onOpen: ignore
  - port: 5555
    name: Prisma Studio
    onOpen: open-browser
  - port: 7910
    name: Storybook
    onOpen: open-browser
  - port: 8910
    name: RedoodJS web application
    onOpen: open-browser
  - port: 8911
    name: Serverless functions
    onOpen: ignore

vscode:
  extensions:
    - "dbaeumer.vscode-eslint"
    - "eamodio.gitlens"
    # - "ofhumanbondage.react-proptypes-intellisense" - Not published to Open VSX (yet)
    - "mgmcdermott.vscode-language-babel"
    - "wix.vscode-import-cost"
    - "pflannery.vscode-versionlens"
    - "editorconfig.editorconfig"
    - "prisma.prisma"
    - "graphql.vscode-graphql"
